Repository dxc-technology/halstack-angular, pull requests merged in 2022-02, with the labels that each got.

#680 [Patch] Card outlined prop default value
  projects/dxc-ngx-cdk-site/src/app/components/examples/card/properties/card-table-properties/card-table-properties.component.html
  projects/dxc-ngx-cdk/src/lib/dxc-card/dxc-card.component.ts
Labels: bug

#684 Types for Heading component
  projects/dxc-ngx-cdk-site/src/app/components/examples/heading/properties/heading-table-properties/heading-table-properties.component.html
  projects/dxc-ngx-cdk/src/lib/dxc-heading/dxc-heading.component.ts
Labels: [PR] type: Type API

#688 Documentation fixes
  projects/dxc-ngx-cdk-site/src/app/components/examples/alert/properties/alert-properties/alert-properties.component.html
  projects/dxc-ngx-cdk-site/src/app/components/examples/card/properties/card-table-properties/card-table-properties.component.html
  projects/dxc-ngx-cdk-site/src/app/components/examples/dropdown/properties/dropdown-table-properties.component.html
  projects/dxc-ngx-cdk-site/src/app/components/examples/header/properties/header-table-properties/header-table-properties.component.html
  projects/dxc-ngx-cdk-site/src/app/components/examples/radio/properties/radio-properties/radio-properties.component.html
  projects/dxc-ngx-cdk-site/src/app/components/examples/tabs/properties/tabs-table-properties.component.html
  projects/dxc-ngx-cdk/src/lib/dxc-alert/dxc-alert.component.ts
  projects/dxc-ngx-cdk/src/lib/dxc-card/dxc-card.component.ts
  projects/dxc-ngx-cdk/src/lib/dxc-checkbox/dxc-checkbox.component.ts
  projects/dxc-ngx-cdk/src/lib/dxc-dropdown/dxc-dropdown.component.ts
  projects/dxc-ngx-cdk/src/lib/dxc-header/dxc-header-dropdown/dxc-header-dropdown.component.ts
  projects/dxc-ngx-cdk/src/lib/dxc-header/dxc-header.component.ts
  projects/dxc-ngx-cdk/src/lib/dxc-radio/dxc-radio.component.ts
  projects/dxc-ngx-cdk/src/lib/dxc-tabs/dxc-tabs.component.ts
Labels: documentation

#693 [Patch] Horizontal scroll in table component
  projects/dxc-ngx-cdk/src/lib/dxc-table/dxc-table.component.ts
Labels: bug

#674 Added wizard types
  projects/dxc-ngx-cdk-site/src/app/components/examples/wizard/properties/wizard-table-properties/wizard-table-properties.component.html
  projects/dxc-ngx-cdk/src/lib/dxc-wizard/dxc-wizard-step/dxc-wizard-step.component.ts
  projects/dxc-ngx-cdk/src/lib/dxc-wizard/dxc-wizard.component.ts
Labels: [PR] type: Type API

#657 [Minor] Types for Footer component
  projects/dxc-ngx-cdk-site/src/app/components/examples/footer/footer-api/footer-api.component.html
  projects/dxc-ngx-cdk-site/src/app/components/examples/footer/properties/footer-table-properties/footer-table-properties.component.html
  projects/dxc-ngx-cdk/src/lib/dxc-footer/dxc-footer.component.ts
  projects/dxc-ngx-cdk/src/lib/variables.ts
Labels: [PR] type: Type API

#678 [Patch] Added marks prop in slider
  projects/dxc-ngx-cdk-site/src/app/pages/theme-builder/previews/slider-preview/slider-preview.component.html
  projects/dxc-ngx-cdk/src/lib/dxc-slider/dxc-slider.component.ts
Labels: bug

#685 Added resultset table types
  projects/dxc-ngx-cdk-site/src/app/components/examples/resultset-table/properties/resultset-table-properties/resultset-table-properties.component.html
  projects/dxc-ngx-cdk-site/src/app/components/examples/resultset-table/resultset-table-directives/resultset-table-directives.component.html
  projects/dxc-ngx-cdk-site/src/app/pages/theme-builder/previews/table-preview/table-preview.component.html
  projects/dxc-ngx-cdk-site/src/app/pages/theme-builder/previews/table-preview/table-preview.component.ts
  projects/dxc-ngx-cdk/src/lib/dxc-resultable/components/dxc-header-row/dxc-header-row.component.ts
  projects/dxc-ngx-cdk/src/lib/dxc-resultable/directives/dxc-column-def.directive.ts
  projects/dxc-ngx-cdk/src/lib/dxc-resultable/table.ts
Labels: [PR] type: Type API

#690 [Patch] Set examples to open first one
  projects/dxc-ngx-cdk-site/src/assets/examples/alert.json
  projects/dxc-ngx-cdk-site/src/assets/examples/app-layout.json
  projects/dxc-ngx-cdk-site/src/assets/examples/autosuggest.json
  projects/dxc-ngx-cdk-site/src/assets/examples/box.json
  projects/dxc-ngx-cdk-site/src/assets/examples/button.json
  projects/dxc-ngx-cdk-site/src/assets/examples/card.json
  projects/dxc-ngx-cdk-site/src/assets/examples/checkbox.json
  projects/dxc-ngx-cdk-site/src/assets/examples/chip.json
  projects/dxc-ngx-cdk-site/src/assets/examples/date.json
  projects/dxc-ngx-cdk-site/src/assets/examples/dialog.json
  projects/dxc-ngx-cdk-site/src/assets/examples/dropdown.json
  projects/dxc-ngx-cdk-site/src/assets/examples/new-date.json
  projects/dxc-ngx-cdk-site/src/assets/examples/new-select.json
  projects/dxc-ngx-cdk-site/src/assets/examples/new-textarea.json
  projects/dxc-ngx-cdk-site/src/assets/examples/newInputText.json
  projects/dxc-ngx-cdk-site/src/assets/examples/select.json
  projects/dxc-ngx-cdk-site/src/assets/examples/tabs.json
  projects/dxc-ngx-cdk-site/src/assets/examples/tag.json
  projects/dxc-ngx-cdk-site/src/assets/examples/text-area.json
  projects/dxc-ngx-cdk-site/src/assets/examples/toggle-group.json
  projects/dxc-ngx-cdk-site/src/assets/examples/upload.json
  projects/dxc-ngx-cdk-site/src/assets/examples/wizard.json
Labels: documentation

#669 Types for Link component
  projects/dxc-ngx-cdk-site/src/app/components/examples/link/properties/link-table-properties/link-table-properties.component.html
  projects/dxc-ngx-cdk/src/lib/dxc-link/dxc-link.component.ts
Labels: [PR] type: Type API

#694 [Patch] Updated documentation
  projects/dxc-ngx-cdk-site/src/app/components/examples/checkbox/properties/checkbox-properties/checkbox-properties.component.html
  projects/dxc-ngx-cdk-site/src/app/components/examples/spinner/properties/spinner-table-properties/spinner-table-properties.component.html
  projects/dxc-ngx-cdk-site/src/app/components/examples/switch/properties/switch-table-properties/switch-table-properties.component.html
Labels: documentation

#711 Added button types.
  projects/dxc-ngx-cdk-site/src/app/components/examples/button/properties/button-table-properties/button-table-properties.component.html
  projects/dxc-ngx-cdk/src/lib/dxc-button/README.md
  projects/dxc-ngx-cdk/src/lib/dxc-button/dxc-button.component.ts
Labels: [PR] type: Type API

#712 Added tag types.
  projects/dxc-ngx-cdk-site/src/app/components/examples/tag/properties/tag-table-properties/tag-table-properties.component.html
  projects/dxc-ngx-cdk/src/lib/dxc-box/dxc-box.component.ts
  projects/dxc-ngx-cdk/src/lib/dxc-tag/README.md
  projects/dxc-ngx-cdk/src/lib/dxc-tag/dxc-tag.component.ts
Labels: [PR] type: Type API

#718 Adding dialog stories
  projects/dxc-ngx-cdk-site/src/app/components/examples/dialog/properties/dialog-table-properties.component.html
  projects/dxc-ngx-cdk/src/lib/dxc-dialog/dxc-dialog.component.ts
  projects/dxc-ngx-cdk/src/lib/dxc-dialog/storybook/default-dialog.stories.html
  projects/dxc-ngx-cdk/src/lib/dxc-dialog/storybook/dialog-large-padding.stories.html
  projects/dxc-ngx-cdk/src/lib/dxc-dialog/storybook/dialog-medium-padding.stories.html
  projects/dxc-ngx-cdk/src/lib/dxc-dialog/storybook/dialog-small-padding.stories.html
  projects/dxc-ngx-cdk/src/lib/dxc-dialog/storybook/dialog-without-close.stories.html
  projects/dxc-ngx-cdk/src/lib/dxc-dialog/storybook/dialog-without-overlay.stories.html
  projects/dxc-ngx-cdk/src/lib/dxc-dialog/storybook/dialog-xlarge-padding.stories.html
  projects/dxc-ngx-cdk/src/lib/dxc-dialog/storybook/dialog-xsmall-padding.stories.html
  projects/dxc-ngx-cdk/src/lib/dxc-dialog/storybook/dialog-xxlarge-padding.stories.html
  projects/dxc-ngx-cdk/src/lib/dxc-dialog/storybook/dialog-xxsmall-padding.stories.html
  projects/dxc-ngx-cdk/src/lib/dxc-dialog/storybook/dxc-dialog.stories.ts
Labels: [PR] type: visual regression
